### ISSUE TITLE
Enforce camelCase/PascalCase code style

### ISSUE THREAD

**Issue by michaelhglass** [SDARG/jreliability#29]
In JReliability, we have several acronyms as part of class and Method names like TMR, but recently we have some more less common acronyms such as BAGT.
Currently:
- BAGTImportanceMeasure
camel/PascalCase:
- BagtImportanceMeasure
- BorgonovoAlieeGlassTeichImportanceMeasure
Both rather long variants look quite strange and in theory we could configure checkstyle to allow acronyms of length n.

What's your opinion @SDARG/jreliability? Strict camelCase/PascalCase which makes live easier as a rule or trying to decide on our own which acronym can directly go into a class/method name. I would like to resolve this before the next (urgent) release to avoid further code refactoring once and for all.

I would opt for strict.

**Comment by FedorSmirnov89** [comment]
I would vote for a strict application of Pascal (classes) and CamelCase (methods).

Just as a personal opinion:

I would name classes in a way where the more abstract part comes first, so that it gets more specific reading left to right, e.g.,

ImportanceMeasureBagt (or MeasureImportanceBagt in case you have different measures).

In addition to being (in my opinion) more natural, this comes with 2 practical editor-related advantages:

(1) It is easier to use in autocomplete: You type ImportanceMeasure and hit ctr + space to see all measures which are there, so you don't need to know their names beforehand.

(2) Since the editor orders the class names alphabetically, you automatically get a grouping following the class hierarchy.

**Comment by michaelhglass** [comment]
OK, let's distinguish two things here:
(1) Strict camelPascalCase would results in strange class names such as Tmr, AbgtImportanceMeasure etc. Those are abbreviations but not acronyms i.e. you don't pronounce [abgt] or [tmr] whereas in LAN you have typically an acronym and a LanConnector wouldn't read that horrible. In the current PR #30, I left all abbreviations in class names and methods. Even codacy doesn't enforce to remove those abbreviations as all-caps, so maybe we can give it a go.

(2) What you suggest is not reflect in most if not all Java styles I'm aware of. It still is HashSet and not SetHash, etc. I think this kind of Hungarian-style Class names could cause more confusion than clarity although there is of course a valid argument to do so in general. This would render a complete renaming of all projects that employ JReliability and if, then this requires a new major release that is not downward compatible across the board.

**Comment by FedorSmirnov89** [comment]
(1) I have no idea about what the mentioned classes are actually doing, but on a general level: I think that a class name with the authors of the underlying concept is not ideal. Would it maybe be possible to pick a name which is descriptive of the content? How do you refer to the corresponding concept in the paper? I would also guess that Codacy would complain about the class name "Tmr" (just because it (rightfully) won't let you use 3 letter names, even for variables).

(2) Yeah, I know :) . Weirdly, the convention in Java is the other way round. And I also agree that it is not worth changing this in projects which are as mature as Opt and co. But at least personally, this is sth that I am doing for all of my new projects since I dislike the Java convention in this point and think that it contributes to a better project structure.
